I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/RPG_fight_scrypt/boss_scene.rpy", line 33, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  [Previous line repeated 3072 more times]
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 130, in script
    if d100 > 15 and rd > 3:
  File "game/RPG_fight_scrypt/boss_scene.rpy", line 33, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  [Previous line repeated 3072 more times]
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 130, in script
    if d100 > 15 and rd > 3:
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "game/RPG_fight_scrypt/boss_scene.rpy", line 33, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  [Previous line repeated 3072 more times]
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 130, in script
    if d100 > 15 and rd > 3:
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/RPG_fight_scrypt/boss_scene.rpy", line 33, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 182, in script call
    call boss_attack
  [Previous line repeated 3072 more times]
  File "game/RPG_fight_scrypt/enemy_round.rpy", line 130, in script
    if d100 > 15 and rd > 3:
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
not_yet_setted 1.0
Sat Nov 30 22:38:21 2024
