I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/act1.rpy", line 11, in script
    menu:
  File "game/act1.rpy", line 12, in <module>
    "去上學" if played_count < 3:
NameError: name 'played_count' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/act1.rpy", line 11, in script
    menu:
  File "C:\Users\USER\Downloads\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 1619, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "C:\Users\USER\Downloads\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\exports\menuexports.py", line 100, in menu
    condition = renpy.python.py_eval(condition)
  File "C:\Users\USER\Downloads\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\USER\Downloads\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/act1.rpy", line 12, in <module>
    "去上學" if played_count < 3:
NameError: name 'played_count' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
not_yet_setted 1.0
Sat Nov 16 23:44:36 2024
