I'm sorry, but an uncaught exception occurred.

Compiling ATL code at game/transform.rpy:3
  File "game/starting.rpy", line 85, in script
    show b glitched
  File "game/transform.rpy", line 3, in <module>
    glitch("b happy") # reliable slicing
NameError: name 'glitch' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/starting.rpy", line 85, in script
    show b glitched
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\display\transform.py", line 1194, in _duplicate
    rv.take_execution_state(self)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\atl.py", line 551, in take_execution_state
    block = self.compile()
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\atl.py", line 723, in compile
    block = self.atl.compile(self.context)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\atl.py", line 925, in compile
    statements = [ i.compile(ctx) for i in self.statements ]
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\atl.py", line 925, in <listcomp>
    statements = [ i.compile(ctx) for i in self.statements ]
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\atl.py", line 1231, in compile
    child = ctx.eval(expr)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\atl.py", line 387, in eval
    return renpy.python.py_eval(expr, locals=self.context)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/transform.rpy", line 3, in <module>
    glitch("b happy") # reliable slicing
NameError: name 'glitch' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
not_yet_setted 1.0
Wed Dec 11 01:05:28 2024
