I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/act4.rpy", line 169, in script
    centerred "彷彿是在抗拒思考一般，你一到家便陷入了沈睡"
Exception: Sayer 'centerred' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/act4.rpy", line 169, in script
    centerred "彷彿是在抗拒思考一般，你一到家便陷入了沈睡"
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/ast.py", line 2573, in execute
    Say.execute(self)
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-8.3.3-sdk/renpy-8.3.3-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'centerred' is not defined.

macOS-12.5-arm64-arm-64bit arm64
Ren'Py 8.3.3.24111502
not_yet_setted 1.0
Thu Dec 12 09:23:11 2024
