I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/boss_scene.rpy", line 50, in script
    if mc.currthoughts > mc.max_thoughts:
  File "game/boss_scene.rpy", line 50, in <module>
    if mc.currthoughts > mc.max_thoughts:
AttributeError: 'fighter' object has no attribute 'currthoughts'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/boss_scene.rpy", line 50, in script
    if mc.currthoughts > mc.max_thoughts:
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\USER\Desktop\renpy-8.3.2-sdk.7z\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/boss_scene.rpy", line 50, in <module>
    if mc.currthoughts > mc.max_thoughts:
AttributeError: 'fighter' object has no attribute 'currthoughts'

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
not_yet_setted 1.0
Sun Nov 24 23:58:22 2024
